server:
  port: 12350

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: welcome

logging:
  level:
    root: warn
    com.zhoushiya.demo: trace
  pattern:
    console: '自定义日志:%p%m%n'